### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by Yelinz** [adopted-ember-addons/ember-changeset#670]
Hello, thanks for the work over the years!

I was wondering if this addon is still being maintained (probably by @snewcomer), as ember v3 has been deprecated for a while.

If you would like some help or so, please tell the community.

**Comment by tschoartschi** [comment]
@Yelinz I asked myself the same question. I think there is this program called "[Adopted Ember Addons](https://github.com/adopted-ember-addons)", maybe this could be an option 🙂

**Comment by SergeAstapov** [comment]
@poteto @snewcomer would you be open to add me as maintainer or transfer addon to https://github.com/adopted-ember-addons ?

**Comment by Gorzas** [comment]
I'm opened to collaborate and give some help, if it's needed.

**Comment by hectorh30** [comment]
Same here, this addon has been very useful to us, so Id be happy to collaborate

**Comment by tschoartschi** [comment]
We upgraded our Ember App to the latest versions (`ember-source`, `ember-data` etc) but ember-changeset gave us lot's of headaches. With the help of the following answer: https://github.com/poteto/ember-changeset/issues/599 we were able to somehow "monkey-patch away" the problems. But I don't think that's a stable base for the future. Not sure how to proceed because the maintainers also do not seem to be responsive. What would be an option to move forward?

**Comment by poteto** [comment]
sorry for not responding sooner! I'm open to transferring it to https://github.com/adopted-ember-addons, I'll need to do that for the core https://github.com/validated-changeset/validated-changeset as well since most of the guts of this addon is implemented there.

**Comment by poteto** [comment]
Update: this has now been moved to adopted-ember-addons! Thanks @knownasilya for all the help!

**Comment by SergeAstapov** [comment]
Thank you @poteto! Is there anything we could help you with the transfer https://github.com/adopted-ember-addons/program-guidelines ? I think most important is to grant permissions for npm and transfer repo, rest we could help with (like updating urls, etc. etc.)

**Comment by SergeAstapov** [comment]
Thank you @poteto!

**Comment by SergeAstapov** [comment]
Repository was transferred to `adopted-ember-addons` organization, I'm now doing some updates to the addon.

FYI for those interested, in my list of things we need to do:
* bump all dependencies of the addon to latest
* sync repo with latest addon blueprint
* convert addon to v2 format
* add TypeScript types
* add exports for `changesetGet`/`changesetSet` template helpers from `ember-changeset` (for Template Tag usage)
* do the same for `ember-changeset-validations` and `validated-changeset` addons
